import Footer from './_components/footer';
import Header from './_components/header';
import './styles/global.css';
import Script from 'next/script';


export const metadata = {
  title: 'Marco Rodrigues - Coaching e Desenvolvimento Pessoal',
  keywords: 'coaching, desenvolvimento pessoal, autoconhecimento, coaching de vida, coaching de carreira, coaching executivo, coaching de liderança',
  description: 'Marco Rodrigues é palestrante internacional, empreendedor e mentor de desenvolvimento pessoal e espiritualidade prática. Ele é especialista em ajudar pessoas a se tornarem a melhor versão de si mesmas e a alcançarem seus objetivos de vida.',
  icons: {
    icon: '/favicon.ico'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">

      <head>
        <meta name="description" content="Generated by Leonardo Valdetaro" />
        <link rel="icon" href="/favicon.png" type="image/png" />

        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-9PEF5DMPG4"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-9PEF5DMPG4');
          `}
        </Script>
        
      </head>

      <body>
        <main className='mainContainer'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
