import Footer from './_components/footer';
import Header from './_components/header';
import './styles/global.css';
import Script from 'next/script';


export const metadata = {
  title: 'Desenvolvimento Pessoal e Profissional com Marco Rodrigues',
  keywords: 'coaching, desenvolvimento pessoal, autoconhecimento, coaching de vida, coaching de carreira, coaching executivo, coaching de liderança, coaching de equipe, coaching de profissionais, performance,produtividade, coaching de espiritualidade, coaching de inteligência emocional, comunicação',
  description: 'Marco Rodrigues é palestrante internacional, empreendedor e mentor de desenvolvimento pessoal e espiritualidade prática. Ele é especialista em ajudar pessoas a se tornarem a melhor versão de si mesmas e a alcançarem seus objetivos de vida.',
  icons: {
    icon: '/favicon.ico'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-pt">

      <head>
        <meta name="description" content="Generated by Leonardo Valdetaro" />

        {/* Favicon híbrido, padrão e usado pelo Google */}
        <link rel="icon" href="/favicon.ico" type="image/ico" />
        {/* Alternância no navegador modo claro/escuro */}
        <link rel="icon" href="/favicon-escuro.png" media="(prefers-color-scheme: light)" type="image/png" />
        <link rel="icon" href="/favicon-claro.png" media="(prefers-color-scheme: dark)" type="image/png" />
        

        <script src="https://cdn.userway.org/widget.js" data-account="U1AlpPUVlr"></script>

        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-9PEF5DMPG4"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-9PEF5DMPG4');
          `}
        </Script>

      </head>

      <body>
        <main className='mainContainer'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
